### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DuckMasterAl** [dredd-bot/Dredd#1]
@TheMoksej you made a lot of typos
https://github.com/TheMoksej/Dredd/blob/master/bot.py#L64-L69

**Comment by TheMoksej** [comment]
What typos are you talking about :/

**Comment by DuckMasterAl** [comment]
@TheMoksej Mutees not Mutes

**Comment by TheMoksej** [comment]
thanks, but well, that works as well haha

**Comment by TheMoksej** [comment]
test ignore this

**Comment by TheMoksej** [comment]
tf did I just do. God I need to learn how to use github properly.

**Comment by DuckMasterAl** [comment]
So now it's an issue? ok...

**Comment by TheMoksej** [comment]
Yes :/

**Comment by TheMoksej** [comment]
Oh look I fixed it
