### ISSUE TITLE
reminder is off by an hour

### ISSUE THREAD

**Issue by ghost** [dredd-bot/Dredd#24]
So in some... Civilised countries we use daylight saving

News: sometimes 17:00 is acctually 5, not 6

**Comment by TheMoksej** [comment]
huh? I dont quite understand why you opened this issue

**Comment by TheMoksej** [comment]
The issue: (will take a bit to find out what's causing the issue cause technically everything is correct)
![Image](https://cdn.dreddbot.xyz/4zMn4P)

**Comment by TheMoksej** [comment]
I'm stupid and didn't realise edwen's time is 1 hour in front of UTC and the bot got the time in UTC, which is fine.
